In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date, datetime, timedelta

pd.set_option('display.max_columns', None)

# Load the dataset
def open_file(file_name: str) -> pd.DataFrame:
    return pd.read_csv(file_name, keep_default_na=False, na_values=[''])


# This creates an ETF column with one label per row.
def assign_etf_label(df, etf_name: str):
    return [etf_name] * len(df)


# This creates an Input_Date column with today's date for every row.
def assign_loading_date(df, input_date=None):
    if input_date is None:
        input_date = date.today()
    return [input_date] * len(df)


# The next block of code loads all holdings from relevant iShares ETFs offered by BlackRock

df_1 = open_file('AQLT.csv')
df_1['ETF'] = assign_etf_label(df_1, 'AQLT')
df_1['Input_Date'] = assign_loading_date(df_1)

df_2 = open_file('IEFA.csv')
df_2['ETF'] = assign_etf_label(df_2, 'IEFA')
df_2['Input_Date'] = assign_loading_date(df_2)

df_3 = open_file('IJH.csv')
df_3['ETF'] = assign_etf_label(df_3, 'IJH')
df_3['Input_Date'] = assign_loading_date(df_3)

df_4 = open_file('IVV.csv')
df_4['ETF'] = assign_etf_label(df_4, 'IVV')
df_4['Input_Date'] = assign_loading_date(df_4)

df_5 = open_file('IWY.csv')
df_5['ETF'] = assign_etf_label(df_5, 'IWY')
df_5['Input_Date'] = assign_loading_date(df_5)

df_6 = open_file('JPXN.csv')
df_6['ETF'] = assign_etf_label(df_6, 'JPXN')
df_6['Input_Date'] = assign_loading_date(df_6)

df_7 = open_file('EFAV.csv')
df_7['ETF'] = assign_etf_label(df_7, 'EFAV')
df_7['Input_Date'] = assign_loading_date(df_7)

df_8 = open_file('QUAL.csv')
df_8['ETF'] = assign_etf_label(df_8, 'QUAL')
df_8['Input_Date'] = assign_loading_date(df_8)

df_iShares = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8], ignore_index=True)
df_iShares.head()

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Quantity,Price,Location,Exchange,Currency,FX Rate,ETF,Input_Date,Accrual Date,Type,Notional Weight,Market Weight,Shares
0,2330,TAIWAN SEMICONDUCTOR MANUFACTURING,Information Technology,Equity,"13,957,310.97",5.88,"13,957,310.97","217,000.00",64.32,Taiwan,Taiwan Stock Exchange,USD,31.48,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN
1,META,META PLATFORMS INC CLASS A,Communication,Equity,"12,166,281.94",5.13,"12,166,281.94","18,134.00",670.91,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN
2,NVDA,NVIDIA CORP,Information Technology,Equity,"11,530,553.90",4.86,"11,530,553.90","57,065.00",202.06,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN
3,AAPL,APPLE INC,Information Technology,Equity,"11,048,149.10",4.66,"11,048,149.10","40,462.00",273.05,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN
4,MSFT,MICROSOFT CORP,Information Technology,Equity,"9,043,690.24",3.81,"9,043,690.24","21,632.00",418.07,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN

In [4]:
df_iShares.info()
#df_iShares.to_csv('my_data.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5017 entries, 0 to 5016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ticker           5017 non-null   object
 1   Name             5017 non-null   object
 2   Sector           5017 non-null   object
 3   Asset Class      5017 non-null   object
 4   Market Value     5017 non-null   object
 5   Weight (%)       4607 non-null   float64
 6   Notional Value   5017 non-null   object
 7   Quantity         4625 non-null   object
 8   Price            5017 non-null   object
 9   Location         5017 non-null   object
 10  Exchange         5017 non-null   object
 11  Currency         5017 non-null   object
 12  FX Rate          5017 non-null   object
 13  ETF              5017 non-null   object
 14  Input_Date       5017 non-null   object
 15  Accrual Date     3070 non-null   object
 16  Type             410 non-null    object
 17  Notional Weight  410 non-null    object
 18  Market Weight    410 non-null    object
 19  Shares           392 non-null    object
dtypes: float64(1), object(19)
memory usage: 784.0+ KB

In [5]:
# The next block of code is for data cleaning

# Test column *names*, not column *values* 

has_weight = 'Weight (%)' in df_iShares.columns
has_market = 'Market Weight' in df_iShares.columns

if has_weight or has_market:
    a = (
        pd.to_numeric(df_iShares['Weight (%)'], errors='coerce')
        if has_weight
        else pd.Series(np.nan, index=df_iShares.index)
    )
    b = (
        pd.to_numeric(df_iShares['Market Weight'], errors='coerce')
        if has_market
        else pd.Series(np.nan, index=df_iShares.index)
    )
    df_iShares['percent'] = a.combine_first(b)  # prefer Weight (%) when both exist


df_iShares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5017 entries, 0 to 5016
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ticker           5017 non-null   object
 1   Name             5017 non-null   object
 2   Sector           5017 non-null   object
 3   Asset Class      5017 non-null   object
 4   Market Value     5017 non-null   object
 5   Weight (%)       4607 non-null   float64
 6   Notional Value   5017 non-null   object
 7   Quantity         4625 non-null   object
 8   Price            5017 non-null   object
 9   Location         5017 non-null   object
 10  Exchange         5017 non-null   object
 11  Currency         5017 non-null   object
 12  FX Rate          5017 non-null   object
 13  ETF              5017 non-null   object
 14  Input_Date       5017 non-null   object
 15  Accrual Date     3070 non-null   object
 16  Type             410 non-null    object
 17  Notional Weight  410 non-null    object
 18  Market Weight    410 non-null    object
 19  Shares           392 non-null    object
 20  percent          5009 non-null   float64
dtypes: float64(2), object(19)
memory usage: 823.2+ KB

In [6]:
# The following code to ingest Vanguard and VanEck etfs

df_Vanguard = open_file('VCN.csv')
df_Vanguard['ETF'] = assign_etf_label(df_Vanguard, 'VCN')
df_Vanguard['Input_Date'] = assign_loading_date(df_Vanguard)

df_SMH = open_file('SMH.csv')
df_SMH['ETF'] = assign_etf_label(df_SMH, 'SMH')
df_SMH['Input_Date'] = assign_loading_date(df_SMH)

df_VanSMH = pd.concat([df_Vanguard, df_SMH], ignore_index=True)
df_VanSMH.head()

df_VanSMH['% of market value'] = pd.to_numeric(
    df_VanSMH['% of market value'].astype(str).str.replace('%', '', regex=False).str.strip(),
    errors='coerce'
)

df_VanSMH['% of market value% of Net Assets'] = pd.to_numeric(
    df_VanSMH['% of Net Assets'].astype(str).str.replace('%', '', regex=False).str.strip(),
    errors='coerce'
)

a = pd.to_numeric(df_VanSMH['% of market value'], errors="coerce")
b = pd.to_numeric(df_VanSMH['% of market value% of Net Assets'], errors="coerce")
df_VanSMH['percent'] = a.combine_first(b) # Weight (%) first

In [7]:
df_VanSMH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Ticker                            244 non-null    object
 1   Holding name                      216 non-null    object
 2   % of market value                 216 non-null    float64
 3   Sector                            216 non-null    object
 4   Region                            216 non-null    object
 5   Market value                      216 non-null    object
 6   Shares                            243 non-null    object
 7   ETF                               245 non-null    object
 8   Input_Date                        245 non-null    object
 9   Number                            27 non-null     float64
 10  Holding Name                      26 non-null     object
 11  Identifier (FIGI)                 26 non-null     object
 12  Asset Class                       27 non-null     object
 13  Market Value (US$)                27 non-null     object
 14  % of Net Assets                   27 non-null     object
 15  % of market value% of Net Assets  27 non-null     float64
 16  percent                           243 non-null    float64
dtypes: float64(4), object(13)
memory usage: 32.7+ KB

In [8]:
df_VanSMH.head()

,Ticker,Holding name,% of market value,Sector,Region,Market value,Shares,ETF,Input_Date,Number,Holding Name,Identifier (FIGI),Asset Class,Market Value (US$),% of Net Assets,% of market value% of Net Assets,percent
0,RY,Royal Bank of Canada,6.8099,Financials,CA,"$987,197,113.92","4,389,884",VCN,2026-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.8099
1,TD,Toronto-Dominion Bank/The,4.7223,Financials,CA,"$684,574,334.08","5,269,199",VCN,2026-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.7223
2,SHOP,Shopify Inc,4.3731,Technology,CA,"$633,950,893.80","3,840,730",VCN,2026-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.3731
3,ENB,Enbridge Inc,3.5563,Energy,CA,"$515,543,858.45","6,836,545",VCN,2026-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5563
4,AEM,Agnico Eagle Mines Ltd,3.0457,Basic Materials,CA,"$441,520,508.88","1,563,624",VCN,2026-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0457

In [9]:
# The following code to ingest Fidelity etfs

df_ftec = open_file('FTEC.csv')
df_ftec['ETF'] = assign_etf_label(df_ftec, 'FTEC')
df_ftec['Input_Date'] = assign_loading_date(df_ftec)

df_fqal = open_file('FQAL.csv')
df_fqal['ETF'] = assign_etf_label(df_fqal, 'FQAL')
df_fqal['Input_Date'] = assign_loading_date(df_fqal)

df_Fidel = pd.concat([df_ftec, df_fqal], ignore_index=True)
df_Fidel.head()

  Symbol                Company  Weight   ETF  Input_Date
0   NVDA            NVIDIA Corp   18.25  FTEC  2026-05-03
1   AAPL              Apple Inc   16.02  FTEC  2026-05-03
2   MSFT         Microsoft Corp   10.29  FTEC  2026-05-03
3   AVGO           Broadcom Inc    4.32  FTEC  2026-05-03
4     MU  Micron Technology Inc    2.01  FTEC  2026-05-03

In [10]:
#Data cleaning step for Fidelity ETFS

df_Fidel['percent'] = df_Fidel['Weight']
df_Fidel['Ticker'] = df_Fidel['Symbol']
df_Fidel.head()

  Symbol                Company  Weight   ETF  Input_Date  percent Ticker
0   NVDA            NVIDIA Corp   18.25  FTEC  2026-05-03    18.25   NVDA
1   AAPL              Apple Inc   16.02  FTEC  2026-05-03    16.02   AAPL
2   MSFT         Microsoft Corp   10.29  FTEC  2026-05-03    10.29   MSFT
3   AVGO           Broadcom Inc    4.32  FTEC  2026-05-03     4.32   AVGO
4     MU  Micron Technology Inc    2.01  FTEC  2026-05-03     2.01     MU

In [11]:
df_Fidel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Symbol      389 non-null    object
 1   Company     400 non-null    object
 2   Weight      400 non-null    float64
 3   ETF         400 non-null    object
 4   Input_Date  400 non-null    object
 5   percent     400 non-null    float64
 6   Ticker      389 non-null    object
dtypes: float64(2), object(5)
memory usage: 22.0+ KB

In [12]:
df_Combined = pd.concat([df_iShares, df_VanSMH,df_Fidel], ignore_index=True)

In [13]:
def ask_hold(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Please enter a number.")

In [14]:
holds = {}
for etf in df_Combined["ETF"].dropna().unique():
    holds[etf] = ask_hold(f"Enter dollar position for this ETF {etf!r}: ")

#If you want a column that repeats the dollar position on every row
df_Combined["my_positions"] = df_Combined["ETF"].map(holds)
df_Combined['my_values'] = df_Combined['my_positions'] * df_Combined['percent'] / 100


# this will be a future function
#my_hold = float(input("Enter your hold of this ETF: "))
#print(f"You entered: {my_hold}")
#df_iShares['my_value'] = df_iShares['percent'] * my_hold

Enter dollar position for this ETF 'AQLT':  100
Enter dollar position for this ETF 'IEFA':  100
Enter dollar position for this ETF 'IJH':  100
Enter dollar position for this ETF 'IVV':  100
Enter dollar position for this ETF 'IWY':  100
Enter dollar position for this ETF 'JPXN':  100
Enter dollar position for this ETF 'EFAV':  100
Enter dollar position for this ETF 'QUAL':  100
Enter dollar position for this ETF 'VCN':  100
Enter dollar position for this ETF 'SMH':  100
Enter dollar position for this ETF 'FTEC':  100
Enter dollar position for this ETF 'FQAL':  100

In [15]:
df_Combined.head()

,Ticker,Name,Sector,Asset Class,Market Value,Weight (%),Notional Value,Quantity,Price,Location,Exchange,Currency,FX Rate,ETF,Input_Date,Accrual Date,Type,Notional Weight,Market Weight,Shares,percent,Holding name,% of market value,Region,Market value,Number,Holding Name,Identifier (FIGI),Market Value (US$),% of Net Assets,% of market value% of Net Assets,Symbol,Company,Weight,my_positions,my_values
0,2330,TAIWAN SEMICONDUCTOR MANUFACTURING,Information Technology,Equity,"13,957,310.97",5.88,"13,957,310.97","217,000.00",64.32,Taiwan,Taiwan Stock Exchange,USD,31.48,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN,5.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.88
1,META,META PLATFORMS INC CLASS A,Communication,Equity,"12,166,281.94",5.13,"12,166,281.94","18,134.00",670.91,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN,5.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,5.13
2,NVDA,NVIDIA CORP,Information Technology,Equity,"11,530,553.90",4.86,"11,530,553.90","57,065.00",202.06,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN,4.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,4.86
3,AAPL,APPLE INC,Information Technology,Equity,"11,048,149.10",4.66,"11,048,149.10","40,462.00",273.05,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN,4.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,4.66
4,MSFT,MICROSOFT CORP,Information Technology,Equity,"9,043,690.24",3.81,"9,043,690.24","21,632.00",418.07,United States,NASDAQ,USD,1,AQLT,2026-05-03,NaN,NaN,NaN,NaN,NaN,3.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,3.81

In [16]:
df_Combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5662 entries, 0 to 5661
Data columns (total 36 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Ticker                            5650 non-null   object
 1   Name                              5017 non-null   object
 2   Sector                            5233 non-null   object
 3   Asset Class                       5044 non-null   object
 4   Market Value                      5017 non-null   object
 5   Weight (%)                        4607 non-null   float64
 6   Notional Value                    5017 non-null   object
 7   Quantity                          4625 non-null   object
 8   Price                             5017 non-null   object
 9   Location                          5017 non-null   object
 10  Exchange                          5017 non-null   object
 11  Currency                          5017 non-null   object
 12  FX Rate                           5017 non-null   object
 13  ETF                               5662 non-null   object
 14  Input_Date                        5662 non-null   object
 15  Accrual Date                      3070 non-null   object
 16  Type                              410 non-null    object
 17  Notional Weight                   410 non-null    object
 18  Market Weight                     410 non-null    object
 19  Shares                            635 non-null    object
 20  percent                           5652 non-null   float64
 21  Holding name                      216 non-null    object
 22  % of market value                 216 non-null    float64
 23  Region                            216 non-null    object
 24  Market value                      216 non-null    object
 25  Number                            27 non-null     float64
 26  Holding Name                      26 non-null     object
 27  Identifier (FIGI)                 26 non-null     object
 28  Market Value (US$)                27 non-null     object
 29  % of Net Assets                   27 non-null     object
 30  % of market value% of Net Assets  27 non-null     float64
 31  Symbol                            389 non-null    object
 32  Company                           400 non-null    object
 33  Weight                            400 non-null    float64
 34  my_positions                      5662 non-null   float64
 35  my_values                         5652 non-null   float64
dtypes: float64(8), object(28)
memory usage: 1.6+ MB

In [19]:
df_Combined.to_csv('my_raw_combined_data.csv', index=False)

In [23]:
# This code generates the list of top 20 stocks held via all etfs combined

total_invested = df_Combined['my_values'].sum()
print("Your total investments are {:.2f}".format(total_invested))

print("Here are your top holdings and percentages")

df_Combined['concentration'] = df_Combined['my_values'] / total_invested

# Sorted totals
df_Combined.groupby("Ticker")["concentration"].sum().sort_values(ascending=False).head(20)

Your total investments are 1200.36
Here are your top holdings and percentages

Ticker
NVDA     0.066088
AAPL     0.044128
MSFT     0.032890
AVGO     0.019786
GOOGL    0.014721
META     0.014312
LRCX     0.011447
KLAC     0.009989
AMAT     0.009539
LLY      0.008906
TSM      0.008831
GOOG     0.008564
V        0.007948
ASML     0.007831
AMZN     0.007281
AMD      0.007256
MU       0.006223
QCOM     0.006015
MA       0.006007
TXN      0.005773
Name: concentration, dtype: float64